version: "2"
services:
  functional-tests:
    extends:
      file: docker-compose.build.yml
      service: mvn
    links:
      - app
      - wiremock
      - db-postgres-reach
    volumes:
      - ../.tools/functional-tests:/scripts/
      - ../functiontest/:$PWD
    environment:
      - HOST=app
      - PORT=8080
    entrypoint: /scripts/wait.sh
    command: mvn -B clean test
    env_file: .env.test

  app:
    image: ${IMAGE}
    expose:
      - 8080
    links:
      - wiremock
      - db-postgres-reach
    env_file: .env
