version: "2"
services:
  jdk:
    image: docker.impello.co.uk/dbi__java17--jdk:17.0.8-3.8.3-4
    volumes:
      - ${PWD}:${PWD}
      - ../.tools/mvn/repository:/usr/share/maven/repository
    working_dir: ${PWD}
    user: ${USER_ID}

  mvn:
    extends:
      service: jdk
    entrypoint: mvn -T 1C
    environment:
      MAVEN_OPTS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
